server:
  tomcat:
    max-swallow-size: 50MB
    max-http-form-post-size: 50MB
  port: 8080
spring:
  application:
    name: jpa-b1
  datasource:
    url: jdbc:mysql://mysql.2tm.store/2tm_dev
    username: 2tm_dev
    password: H9D%L5mdgtKEP@sN
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: remxram2003@gmail.com
    password: kuan scqj oaaz qwlm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  signerKey: 3331QGQ7lwcpqMeuVGSCjPkwkMKk/92td+suEztit4FWXPXwLjjxmnHY0Knj796r
  valid-duration: 3600 # in second
  refreshable-duration: 86400
open:
  api:
    title: 2TM API Documentation 
    description: this is a test api documentation for 2TM project 
    version: 1.0.0
    serverUrl: https://api.2tm.store/
    serverName: server test
infobip:
  apiKey: 4417fd3b84080411b22ef1229ac29ee6-1e8c5e94-631c-401c-aa79-b75f5a2e2cff
  baseUrl: https://e1nzd1.api.infobip.com
  senderPhoneNumber: 84337619959
