server:
  tomcat:
    max-swallow-size: 50MB
    max-http-form-post-size: 50MB
  port: 8080
spring:
  application:
    name: jpa-b1
  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/STORE_TEST
    username: 2zgSHt1FxfMnZVN.root
    password: p98eOXMEDmKam2qJ
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: 3331QGQ7lwcpqMeuVGSCjPkwkMKk/92td+suEztit4FWXPXwLjjxmnHY0Knj796r
  valid-duration: 3600 # in second
  refreshable-duration: 86400
